# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'BTCompTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BTCompTest

  target 'BTCompTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BTCompTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'SnapKit'
  pod 'NHNetworkTime'

end
